package com.patreonkt.auth

import okhttp3.Cookie
import okhttp3.CookieJar
import okhttp3.HttpUrl
import java.io.File
import java.util.concurrent.ConcurrentHashMap

/**
 * OkHttp [CookieJar] that persists session cookies in the Netscape cookie file format.
 *
 * On construction the jar optionally loads an existing cookie file. Call [saveToFile] to flush
 * the in-memory store back to disk after successful authentication.
 *
 * ### Netscape format
 * Each line follows: `domain  TRUE  path  secure  expiry  name  value`
 *
 * @param cookieFile Optional Netscape-format cookie file to load on initialisation.
 */
class PatreonCookieJar(cookieFile: File? = null) : CookieJar {

    private val store = ConcurrentHashMap<String, MutableList<Cookie>>()

    init {
        cookieFile?.takeIf { it.exists() }?.let { loadFromFile(it) }
    }

    override fun saveFromResponse(url: HttpUrl, cookies: List<Cookie>) {
        val host = url.host
        store.getOrPut(host) { mutableListOf() }.apply {
            cookies.forEach { incoming ->
                removeIf { existing -> existing.name == incoming.name }
                add(incoming)
            }
        }
    }

    override fun loadForRequest(url: HttpUrl): List<Cookie> =
        store[url.host]?.filter { it.matches(url) } ?: emptyList()

    /**
     * Adds cookies directly (e.g. harvested from a WebView session).
     */
    fun addCookies(host: String, cookies: List<Cookie>) {
        store.getOrPut(host) { mutableListOf() }.apply {
            cookies.forEach { incoming ->
                removeIf { it.name == incoming.name }
                add(incoming)
            }
        }
    }

    /** Returns a flat list of all stored cookies across all hosts. */
    fun allCookies(): List<Cookie> = store.values.flatten()

    /** Returns a `Cookie: name=value; name2=value2` header string for [host]. */
    fun cookieHeaderFor(host: String): String =
        store[host]?.joinToString("; ") { "${it.name}=${it.value}" } ?: ""

    /**
     * Persists all cookies to [file] in Netscape format.
     * Lines starting with `#` are comment headers written automatically.
     */
    fun saveToFile(file: File) {
        val sb = StringBuilder("# Netscape HTTP Cookie File\n# Generated by patreon-kt\n\n")
        store.values.flatten().forEach { c ->
            sb.append("${c.domain}\tTRUE\t${c.path}\t${c.secure}\t${c.expiresAt / 1000}\t${c.name}\t${c.value}\n")
        }
        file.parentFile?.mkdirs()
        file.writeText(sb.toString())
    }

    private fun loadFromFile(file: File) {
        file.forEachLine { line ->
            if (line.startsWith("#") || line.isBlank()) return@forEachLine
            val parts = line.split("\t")
            if (parts.size < 7) return@forEachLine
            val (domain, _, path, secureStr, expiryStr, name, value) = parts
            val host = domain.trimStart('.')
            val cookie = Cookie.Builder()
                .domain(host)
                .path(path)
                .name(name)
                .value(value)
                .apply {
                    if (secureStr.equals("true", ignoreCase = true)) secure()
                    val expiry = expiryStr.toLongOrNull() ?: 0L
                    if (expiry > 0) expiresAt(expiry * 1000)
                }
                .build()
            store.getOrPut(host) { mutableListOf() }.add(cookie)
        }
    }
}

private operator fun <T> List<T>.component6(): T = get(5)
private operator fun <T> List<T>.component7(): T = get(6)
